# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fab95b74fb16308fc7b6d2fcf9c7cf76879be54fc6a14c506af6bae88db1aafcd82b630d8abd3846b3c2d88464f3fd7079a4dcbf068ad6a831ef98ac4d63233b

test:
  secret_key_base: 687aed596f76ad3f71fc876e8a05b92f3220cf5548cbbbba2f8cca38770936df85161232d4b8f29bb88ad4437774b250f683552dc0c0dc8840ceb160aeda16b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
